import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class TipsOfTheDayPage extends StatefulWidget {
  @override
  _TipsOfTheDayPageState createState() => _TipsOfTheDayPageState();
}

class _TipsOfTheDayPageState extends State<TipsOfTheDayPage> {
  final List<String> tips = [
  "Stay hydrated. Drink at least 8 cups of water today!",
  "Take a walk outside to get some fresh air and sunlight.",
  "Practice deep breathing for 5 minutes to relieve stress.",
  "Set a goal for today and accomplish at least one task.",
  "Don't forget to take breaks while working to avoid burnout.",
  "Eat a balanced diet with more fruits and vegetables.",
  "Remember to smile and spread positivity around you.",
  "Try a new healthy recipe today.",
  "Spend time with a loved one or friend.",
  "Meditate for 10 minutes to calm your mind.",
  "Listen to your favorite music to lift your spirits.",
  "Get at least 7-8 hours of sleep tonight.",
  "Write down three things you are grateful for.",
  "Do some gentle stretching to increase flexibility.",
  "Limit screen time and take regular breaks from devices.",
  "Practice good posture throughout the day.",
  "Drink herbal tea to relax before bedtime.",
  "Read a book or article that interests you.",
  "Try a hobby or activity you enjoy.",
  "Laugh out loud – it’s good for your health!",
  "Organize a small space in your home to feel productive.",
  "Avoid sugary snacks; choose fruit instead.",
  "Spend a few minutes in nature.",
  "Write a journal entry about your day.",
  "Practice mindfulness while eating – savor each bite.",
  "Call or message someone to check in on them.",
  "Do 15 minutes of light exercise.",
  "Declutter your workspace for better focus.",
  "Avoid caffeine late in the day.",
  "Try aromatherapy with essential oils for relaxation.",
  "Visualize a positive outcome for your day.",
  "Practice saying positive affirmations.",
  "Take a warm bath to soothe your muscles.",
  "Avoid multitasking; focus on one task at a time.",
  "Set a reminder to drink water regularly.",
  "Try a puzzle or brain game to stimulate your mind.",
  "Spend time petting or playing with a pet.",
  "Eat slowly and mindfully to improve digestion.",
  "Reduce noise around you with calming sounds or music.",
  "Try a new form of exercise like yoga or tai chi.",
  "Plan a fun outing or mini-adventure.",
  "Practice forgiveness to lighten your emotional load.",
  "Take deep breaths when feeling anxious.",
  "Avoid negative self-talk; be kind to yourself.",
  "Limit alcohol consumption.",
  "Use a standing desk or change positions often.",
  "Get some sunlight in the morning to regulate your body clock.",
  "Write a letter or note to someone you appreciate.",
  "Try progressive muscle relaxation techniques.",
  "Spend time coloring or drawing to relax.",
  "Focus on your senses: notice smells, sounds, and textures.",
  "Try a digital detox for a few hours.",
  "Practice gratitude before going to sleep.",
  "Prepare a healthy snack to enjoy later.",
  "Set a timer to remind yourself to stretch hourly.",
  "Take a few minutes to organize your schedule.",
  "Practice good hand hygiene to stay healthy.",
  "Avoid heavy meals close to bedtime.",
  "Learn something new online or from a book.",
  "Plan your week ahead to reduce stress.",
  "Avoid negative news before bed.",
  "Try gentle massages or self-massage techniques.",
  "Keep a water bottle handy all day.",
  "Eat more fiber-rich foods for digestion.",
  "Practice visualization techniques for relaxation.",
  "Spend time gardening or with plants.",
  "Challenge yourself to smile more today.",
  "Set a small daily goal to build momentum.",
  "Try to limit processed foods.",
  "Avoid excessive salt intake.",
  "Use positive language when speaking to others.",
  "Create a calming bedtime routine.",
  "Avoid heavy use of social media.",
  "Wear comfortable clothes to boost mood.",
  "Practice deep squats or simple strength exercises.",
  "Set boundaries to protect your mental health.",
  "Try a new fruit or vegetable.",
  "Practice patience in stressful situations.",
  "Spend time in silence to center yourself.",
  "Avoid eating while distracted by TV or phone.",
  "Practice gentle neck and shoulder stretches.",
  "Try a new breathing pattern to calm anxiety.",
  "Spend 10 minutes decluttering a small area.",
  "Write down a personal achievement each day.",
  "Prepare a nutritious breakfast to start your day.",
  "Avoid skipping meals to maintain energy.",
  "Learn to say no to unnecessary commitments.",
  "Make time for self-care activities today.",
  "Keep a gratitude jar and add notes regularly.",
  "Avoid comparing yourself to others.",
  "Set an intention for your day each morning.",
  "Practice kindness to strangers and yourself.",
  "Drink a glass of water before each meal.",
  "Limit sugar intake by choosing natural sweets.",
  "Spend a few minutes watching the sunset or sunrise.",
  "Try mindful walking focusing on each step.",
  "Avoid late-night screen time to improve sleep.",
  "Keep a list of activities that make you happy.",
  "Create a relaxing playlist for stressful moments.",
  "Practice grounding techniques when anxious.",
  "Try replacing one cup of coffee with green tea.",
  "Celebrate small wins and progress.",
  "Practice yoga or stretching before bed.",
    "Start your day with a glass of warm lemon water.",
  "Try journaling your thoughts for 5 minutes each morning.",
  "Practice gratitude by thanking someone today.",
  "Take the stairs instead of the elevator.",
  "Avoid multitasking to increase productivity.",
  "Spend 10 minutes doing deep stretches after waking up.",
  "Try a new fruit smoothie recipe for a healthy snack.",
  "Set a timer to remind yourself to blink often during screen time.",
  "Replace one sugary drink with water daily.",
  "Practice good dental hygiene: floss and brush twice daily.",
  "Limit your sitting time to less than 30 minutes at a stretch.",
  "Learn a few words in a new language.",
  "Try a meatless day and enjoy plant-based meals.",
  "Do something creative like painting or crafting.",
  "Spend time listening to a podcast that interests you.",
  "Organize your digital files or photos.",
  "Try to laugh at least 3 times today.",
  "Practice a random act of kindness.",
  "Try grounding by walking barefoot on grass or sand.",
  "Create a relaxing nighttime ritual to improve sleep quality.",
  "Eat your meals without distractions like TV or phone.",
  "Try a guided meditation app for 10 minutes.",
  "Write a thank-you note to someone who helped you.",
  "Set a specific time to check emails and stick to it.",
  "Explore a new walking or hiking trail nearby.",
  "Do some light gardening or care for a houseplant.",
  "Unplug from all electronic devices for an hour.",
  "Try new herbal teas for relaxation or digestion.",
  "Listen to calming nature sounds during work breaks.",
  "Cook a meal from a cuisine you’ve never tried before.",
  "Start a savings jar for something special.",
  "Practice balancing exercises for better coordination.",
  "Take a midday power nap of 15-20 minutes.",
  "Make a playlist of songs that boost your mood.",
  "Try a new breathing exercise called box breathing.",
  "Write a list of things that make you happy.",
  "Plan a day without commitments to relax and recharge.",
  "Take a different route for your daily walk.",
  "Explore local museums or cultural sites virtually.",
  "Add nuts and seeds to your diet for healthy fats.",
  "Try foam rolling to relieve muscle tension.",
  "Practice mindful listening during conversations.",
  "Declutter your email inbox.",
  "Make a list of books you want to read this year.",
  "Try a 5-minute dance break to energize yourself.",
  "Avoid eating late at night to support digestion.",
  "Set up a cozy reading nook in your home.",
  "Use positive visualization to handle stressful events.",
  "Try progressive relaxation before bedtime.",
  "Go tech-free during meals with family or friends.",
  "Take a photo of something beautiful each day.",
  "Drink a cup of green tea for antioxidants.",
  "Practice hand reflexology or acupressure points.",
  "Write down your favorite motivational quotes.",
  "Limit caffeine after 2 PM to avoid sleep disturbances.",
  "Practice saying ‘no’ kindly but firmly when overwhelmed.",
  "Try a new form of physical activity like swimming or cycling.",
  "Have a device-free hour before bed for better sleep.",
  "Cook with more herbs and spices for flavor and health benefits.",
  "Try guided imagery to relax your mind.",
  "Clean or reorganize your living space for clarity.",
  "Take breaks every hour to stand and move.",
  "Drink water infused with cucumber or mint for freshness.",
  "Avoid comparing yourself on social media.",
  "Write down three things you did well today.",
  "Replace processed snacks with whole foods.",
  "Practice meditation focusing on body sensations.",
  "Have a gratitude conversation with a friend.",
  "Try using a standing desk or work while standing.",
  "Set a daily intention or mantra to guide your actions.",
  "Limit news consumption to reduce anxiety.",
  "Engage in volunteer work or community service.",
  "Cook a meal with family or friends to bond.",
  "Practice mindfulness during your commute.",
  "Try a new sport or outdoor activity.",
  "Make a vision board of your goals and dreams.",
  "Keep a hydration tracker to remind you to drink water.",
  "Create a sleep-friendly environment: cool, dark, and quiet.",
  "Write a letter to your future self.",
  "Use laughter yoga techniques to boost mood.",
  "Try cold showers to invigorate your body.",
  "Reduce salt intake to support heart health.",
  "Engage in positive self-talk daily.",
  "Try alternating nostril breathing to reduce stress.",
  "Spend time decluttering your wardrobe.",
  "Create a meal plan for the week to eat healthier.",
  "Practice self-compassion during tough times.",
  "Dance like no one is watching to relieve tension.",
  "Spend time reflecting on your achievements monthly.",
  "Turn off notifications to minimize distractions.",
  "Try a gratitude meditation before sleeping.",
  "Use a journal to track moods and triggers.",
  "Avoid sugar-laden breakfast cereals.",
  "Make time for a hobby you love every week.",
  "Take a walk after meals to aid digestion.",
  "Set boundaries around work and personal time.",
  "Add more colorful fruits and veggies to your plate.",
  "Practice smiling to improve your mood.",
  "Use a daily planner to organize tasks.",
  "Make homemade smoothies instead of buying processed drinks.",
  "Try simple yoga poses to stretch and relax.",
  "Limit alcohol consumption to special occasions.",
  "Celebrate small victories in your wellness journey.",
  "Stay consistent with your bedtime routine.",
  "Practice empathy and listen actively to others.",
  "Replace negative thoughts with positive ones.",
  "Take a break to watch the clouds or stars.",
  "Spend 10 minutes doing gratitude journaling.",
  "Be kind to yourself and practice self-love.",
  "Try a new tea blend for relaxation before bed.",
  "Write down three positive things about yourself.",
  "Use natural light during the day to boost mood.",
  "Avoid skipping breakfast for steady energy."
];


  String currentTip = "";

  // Function to get a random tip
  void getRandomTip() {
    final randomTip = (tips..shuffle()).first;
    setState(() {
      currentTip = randomTip;
    });
  }

  @override
  void initState() {
    super.initState();
    getRandomTip(); // Initialize with a random tip when the page is loaded
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFFEACCA9), // Scaffold background color
      appBar: AppBar(
        foregroundColor: Color(0xFFEACCA9),
        title: Text(
          "Tips of the Day",
          style: GoogleFonts.merriweather(
            fontWeight: FontWeight.bold,
            color: Color(0xFFEACCA9),
          ),
        ),
        backgroundColor: Color(0xFF755b48), // AppBar background color
      ),
      body: Center(
        child: Card(
          color: Color(0xFFfcefdc), // Card background color
          margin: EdgeInsets.all(24),
          elevation: 6,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(
                  Icons.lightbulb,
                  size: 60,
                  color: Color(0xFF755b48), // Icon color
                ),
                SizedBox(height: 20),
                Text(
                  "Tip of the Day:",
                  style: GoogleFonts.merriweather(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFF755b48),
                  ),
                ),
                SizedBox(height: 16),
                Text(
                  currentTip,
                  style: GoogleFonts.merriweather(
                    fontSize: 18,
                    fontStyle: FontStyle.italic,
                    color: Color(0xFF755b48),
                  ),
                  textAlign: TextAlign.center,
                ),
                SizedBox(height: 30),
                ElevatedButton(
                  onPressed: getRandomTip,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Color(0xFF755b48), // Button background color
                    padding: EdgeInsets.symmetric(horizontal: 30, vertical: 15),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  child: Text(
                    "Get New Tip",
                    style: GoogleFonts.merriweather(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                      color: Color(0xFFEACCA9), // Button text color
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
